#!/usr/bin/env bash
# PR preparation script — generated by issue-workspace skill
# Syncs code changes from the dev branch to a clean PR worktree.
# Edit BASE_BRANCH, ISSUE_NUMBER, and ISSUE_TITLE_SLUG before first use.
set -euo pipefail

# ─── Configuration (filled in by issue-workspace setup) ───────────────────────
BASE_BRANCH="{{BASE_BRANCH}}"
ISSUE_NUMBER="{{ISSUE_NUMBER}}"
ISSUE_TITLE_SLUG="{{ISSUE_TITLE_SLUG}}"
# ──────────────────────────────────────────────────────────────────────────────

DEV_BRANCH="local/issue/${ISSUE_NUMBER}"
PR_BRANCH="feat/issue-${ISSUE_NUMBER}/${ISSUE_TITLE_SLUG}"
MEMORY_DIR="$(cd "$(dirname "$0")" && pwd)"
WORKTREE_PATH="${MEMORY_DIR}/worktree"
REPO_ROOT="$(git -C "${MEMORY_DIR}" rev-parse --show-toplevel)"

log() { printf '\033[1;34m[pr-prep]\033[0m %s\n' "$*"; }
ok()  { printf '\033[1;32m[ok]\033[0m %s\n' "$*"; }
err() { printf '\033[1;31m[error]\033[0m %s\n' "$*" >&2; exit 1; }

# ─── Validate current state ───────────────────────────────────────────────────
log "Checking current branch..."
CURRENT_BRANCH="$(git -C "${REPO_ROOT}" rev-parse --abbrev-ref HEAD)"
if [[ "${CURRENT_BRANCH}" != "${DEV_BRANCH}" ]]; then
  err "Must be on '${DEV_BRANCH}', currently on '${CURRENT_BRANCH}'"
fi

# ─── Ensure PR branch exists ──────────────────────────────────────────────────
log "Ensuring PR branch '${PR_BRANCH}' exists..."
if ! git -C "${REPO_ROOT}" show-ref --quiet "refs/heads/${PR_BRANCH}"; then
  git -C "${REPO_ROOT}" branch "${PR_BRANCH}" "${BASE_BRANCH}"
  ok "Created PR branch '${PR_BRANCH}' from '${BASE_BRANCH}'"
else
  ok "PR branch '${PR_BRANCH}' already exists"
fi

# ─── Ensure worktree exists ───────────────────────────────────────────────────
log "Ensuring worktree at '${WORKTREE_PATH}'..."
if ! git -C "${REPO_ROOT}" worktree list | grep -qF "${WORKTREE_PATH}"; then
  git -C "${REPO_ROOT}" worktree add "${WORKTREE_PATH}" "${PR_BRANCH}"
  ok "Worktree created at '${WORKTREE_PATH}'"
else
  ok "Worktree already exists"
fi

# ─── Collect code-only commits from dev branch ────────────────────────────────
log "Collecting commits to sync (excluding .memory/)..."

COMMITS_TO_APPLY="$(
  git -C "${REPO_ROOT}" log \
    --reverse \
    --format="%H" \
    "${BASE_BRANCH}..${DEV_BRANCH}" \
    -- \
    ':!.memory/**' \
    ':!.gitignore'
)"

if [[ -z "${COMMITS_TO_APPLY}" ]]; then
  log "No code commits to apply. Worktree is up to date."
  exit 0
fi

# ─── Apply commits to PR branch via worktree ─────────────────────────────────
log "Applying commits to '${PR_BRANCH}'..."
APPLIED=0
SKIPPED=0

while IFS= read -r commit; do
  [[ -z "${commit}" ]] && continue

  CHANGED_FILES="$(git -C "${REPO_ROOT}" diff-tree --no-commit-id -r --name-only "${commit}")"
  CODE_FILES="$(echo "${CHANGED_FILES}" | grep -v '^\.memory/' || true)"

  if [[ -z "${CODE_FILES}" ]]; then
    SKIPPED=$((SKIPPED + 1))
    continue
  fi

  COMMIT_MSG="$(git -C "${REPO_ROOT}" log -1 --format="%s" "${commit}")"

  # Check if commit is already in PR branch (avoid duplicates)
  if git -C "${WORKTREE_PATH}" log --format="%s" "${PR_BRANCH}" 2>/dev/null | grep -qF "${COMMIT_MSG}"; then
    log "  skip (already applied): ${COMMIT_MSG}"
    SKIPPED=$((SKIPPED + 1))
    continue
  fi

  # Apply only the code files from this commit
  git -C "${REPO_ROOT}" diff "${commit}^..${commit}" -- ${CODE_FILES} \
    | git -C "${WORKTREE_PATH}" apply --index --whitespace=nowarn 2>/dev/null || {
      log "  conflict on '${COMMIT_MSG}' — applying with 3-way merge..."
      git -C "${REPO_ROOT}" diff "${commit}^..${commit}" -- ${CODE_FILES} \
        | git -C "${WORKTREE_PATH}" apply --index --3way --whitespace=nowarn || true
    }

  git -C "${WORKTREE_PATH}" commit -m "${COMMIT_MSG}" --allow-empty 2>/dev/null || true
  ok "  applied: ${COMMIT_MSG}"
  APPLIED=$((APPLIED + 1))
done <<< "${COMMITS_TO_APPLY}"

# ─── Summary ──────────────────────────────────────────────────────────────────
echo ""
ok "PR worktree ready"
echo "  Dev branch  : ${DEV_BRANCH}"
echo "  PR branch   : ${PR_BRANCH}"
echo "  Worktree    : ${WORKTREE_PATH}"
echo "  Commits applied : ${APPLIED}"
echo "  Commits skipped : ${SKIPPED}"
echo ""
echo "Next: review changes in '${WORKTREE_PATH}', then use pr-creator skill to open the PR."
